import * as CONTROLLERS from './controllers';

export const ROOT = '/api/v1' as const;

export const REST_API = {
    AUTH: {
        LOGIN: `${ROOT}/${CONTROLLERS.AUTH_CONTROLLER}/${CONTROLLERS.AUTH_ROUTES.LOGIN}`,
        REGISTER: `${ROOT}/${CONTROLLERS.AUTH_CONTROLLER}/${CONTROLLERS.AUTH_ROUTES.REGISTER}`,
    },
    USER: {
        GET_ME: `${ROOT}/${CONTROLLERS.USER_CONTROLLER}/${CONTROLLERS.USER_ROUTES.GET}`,
    },
    PRODUCTS: {
        CREATE: `${ROOT}/${CONTROLLERS.PRODUCTS_CONTROLLER}/${CONTROLLERS.PRODUCTS_ROUTES.CREATE}`,
        GET_BY_UUID: `${ROOT}/${CONTROLLERS.PRODUCTS_CONTROLLER}/${CONTROLLERS.PRODUCTS_ROUTES.GET_BY_UUID}`,
        GET_ALL: `${ROOT}/${CONTROLLERS.PRODUCTS_CONTROLLER}/${CONTROLLERS.PRODUCTS_ROUTES.GET_ALL}`,
        DELETE: `${ROOT}/${CONTROLLERS.PRODUCTS_CONTROLLER}/${CONTROLLERS.PRODUCTS_ROUTES.DELETE}`,
    },
    PURCHASES: {
        CREATE: `${ROOT}/${CONTROLLERS.PURCHASES_CONTROLLER}/${CONTROLLERS.PURCHASES_ROUTES.CREATE}`,
    },
} as const;
